### ISSUE TITLE
文字错误

### ISSUE THREAD

**Issue by RyoLee** [tatsuz0u/EhPanda#10]
"登陆"应为"登录"

**Comment by tatsuz0u** [comment]
您好，关于这一点，其实是因为在写这一块的时候我认为应该使用“登陆”，我会去核实一下情况，并修改为较为不具争议性的内容。

**Comment by tatsuz0u** [comment]
已在 https://github.com/tatsuz0u/EhPanda/commit/3d766fbda5d019641f78d7e771a8aa59aa9783d6 修复。
