### ISSUE TITLE
[BUG] Autoplay button unexpected layout

### ISSUE THREAD

**Issue by mrniceguy999** [tatsuz0u/EhPanda#149]
**Describe the bug**
Autoplay button glitches(disappears/only displays partly)

**To Reproduce**
1. Read a certain manga
2. Click on the center of the screen
3. See error

**Expected behavior**
Autoplay button glitches when menu appears.

**Screenshots**
![image](https://user-images.githubusercontent.com/34647295/134804286-ffbe7645-8eaf-44bd-90fb-3e817dbf2b10.jpeg)

 - Device: [iPhone 11 Pro Max]
 - OS: [iOS 15.0]
 - App Version [v1.3.3_b114]

**Comment by tatsuz0u** [comment]
Thanks for your feedback. I'll look into it.

**Comment by tatsuz0u** [comment]
Done. 59b3eb9d3f8783c34b6695a6b88b0b6d56dee8d3
