### ISSUE TITLE
exhentai仅能加载两张图

### ISSUE THREAD

**Issue by errorfg** [tatsuz0u/EhPanda#15]
在登陆ex并获取igneous后尽管能加载出搜索界面，但子界面仅加载2张图，点击阅读提示网络错误，同一设备同一账号可在网页版访问同一本子
![IMG_7E52C74E2D30-1 2](https://user-images.githubusercontent.com/18473413/120120189-4cbfe400-c1ce-11eb-892d-08160860ea53.jpeg)
![IMG_DF1494195E9B-1](https://user-images.githubusercontent.com/18473413/120120193-50ec0180-c1ce-11eb-83b0-2f7ef76dc37d.jpeg)
![IMG_6E1B987AB61D-1](https://user-images.githubusercontent.com/18473413/120120198-55181f00-c1ce-11eb-8d2a-d7f56384cbb2.jpeg)
![IMG_D4E985712BED-1](https://user-images.githubusercontent.com/18473413/120120201-5ba69680-c1ce-11eb-9cca-feab28563661.jpeg)

**Comment by tatsuz0u** [comment]
您好，

這看起來解析器設計上存在重大缺陷...
我會嘗試復現它，謝謝您的反饋。

**Comment by tatsuz0u** [comment]
經確認，問題可能是因為EhPanda無法將您的縮略圖設置為large樣式，這很可能同時影響到了閱讀頁的數據解析，可以請您先讓帳號處於能夠設置large的狀態嗎？

**Comment by tatsuz0u** [comment]
因決定支持normal預覽，本issue重新定性為bug。

**Comment by tatsuz0u** [comment]
Fixed in v1.0.3 b53 version.
