### ISSUE TITLE
[Feature Request] Save original image

### ISSUE THREAD

**Issue by akinokoika** [tatsuz0u/EhPanda#155]
**能否添加下载/保存原图的功能**
长按保存图片时保存的是默认分辨率的图片，即使在账号的订阅设置里修改图片分辨率到2400x也只是可以保存最大2400x的图片，而自己在其他设备保存过的同一张图片的原图分辨率是2800x，并且文件大小800kb也远远小于原图的7mb
虽然这个功能会触发账号的下载配额限制，但还是希望可以添加，这对在ipp上浏览有很大帮助，谢谢

**Comment by tatsuz0u** [comment]
好的。

**Comment by tatsuz0u** [comment]
Done. ad97690

**Comment by aishaxx** [comment]
保存原图失败什么意思，还有赞助多少能2400

**Comment by aishaxx** [comment]
> 是
