### ISSUE TITLE
[Enhancement] Removal of galleries in list after switching gallery host

### ISSUE THREAD

**Issue by fireflych** [tatsuz0u/EhPanda#156]
**Describe the bug**
The app still using e-hentai  after switch to exhentai in account settings

**To Reproduce**
1. Change as exhentai in account settings 
2. Browse any gallery 
3. In log still using e-hentai 

**Expected behavior**
Should access exhentai gallery after change the account settings 

**Screenshots**
![124CC6FB-322B-4CF2-AC05-F671B4A7CD6C](https://user-images.githubusercontent.com/1292314/135134154-ea7bb7e7-c03d-4334-bad2-187fcbd4510a.jpeg)

![3E03CCE4-F4A2-4796-837D-FF7CC39F2B9D](https://user-images.githubusercontent.com/1292314/135134385-34a9cb9d-e70e-445b-bc39-56c0be51cf59.png)

**Please complete the following information:**
 - Device:  iPhone 13
 - OS: iOS 15
 - App Version 1.3.6

**Additional context**

**Comment by tatsuz0u** [comment]
Well, in fact, it did switch to another host. But the fetched galleries in list are not removed, it could be misleading indeed.
I'll look into it, thanks for bringing this up.

**Comment by tatsuz0u** [comment]
Done. 5c05016
