### ISSUE TITLE
[Feature Request] Tap to go prev / next page & Quick search query alias

### ISSUE THREAD

**Issue by glm941214** [tatsuz0u/EhPanda#157]
**Is your feature request related to a problem? Please describe.**
1. 左右翻页动画无法关闭
2. 快速搜索无法添加别称

**Describe the solution you'd like**
 1. 左右翻页希望可以添加点击两侧无过渡动画翻页
 2. 快速搜索希望可以添加别称，因为有些查询是多个标签组合起来的，所以希望能允许用户自定义一个别称概括

**Comment by tatsuz0u** [comment]
至少點擊左右翻頁這個看起來挺值得做的，沒問題。

**Comment by tatsuz0u** [comment]
Done. b3728bd
