### ISSUE TITLE
failed to install the ipa on ios 15.1 with AsTools signed

### ISSUE THREAD

**Issue by jhxxs** [tatsuz0u/EhPanda#158]
**Describe the bug**
Using AsTools(爱思助手最新版) to sign the ipa with my own apple account, after signing, i try to install the ipa, but it failed.

**Expected behavior**
ipa could be installed successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/7448223/135752579-37db8ded-cdca-4f8e-b0ef-c9861fa05fe7.png)
![image](https://user-images.githubusercontent.com/7448223/135752651-b7f78f21-c626-40da-93f5-3762f4793947.png)

**Please complete the following information:**
 - Device:  iPhone Xr
 - OS: 15.1
 - App Version:  v1.3.6_b117

**Additional context**
用爱思助手签名之后安装失败，是不是我下载的版本不对？提示的是越狱版。

**Comment by tatsuz0u** [comment]
I'm not sure if EhPanda works fine with iOS 15.1 beta.
Can you try this build? [v1.3.1](https://github.com/tatsuz0u/EhPanda/releases/tag/v1.3.1_b112)

Anyway, normally I don't answer questions about installation, so I'm closing this issue.
Please feel free to reopen it if you have a good reason to think that there's problems with the ipa file.

**Comment by Qiu-INJ** [comment]
`[
![2021-10-07 13-24-46 的屏幕截图](https://user-images.githubusercontent.com/85727393/136324897-f7d1ab2c-8186-46d0-a8ea-f16085208c73.png)
](url)`

**Comment by tatsuz0u** [comment]
> linux, ubuntu 18, libimobiledevice
> 
> command:
> 
> ```ideviceinstaller -i ./EhPanda.ipa -o my_iphone_uuid```

Did you resign the ipa file? 🤔

**Comment by Ljzd-PRO** [comment]
Sideloadly和爱思助手都无法安装。
Sideloadly提示：
```
FAILED: Call to afc_file_close failed: AFC_E_MUX_ERROR
```
爱思助手提示：
```
AppexBundleIDNotPrefixed
```
不知道这些信息有没有用

**Comment by Ljzd-PRO** [comment]
> Sideloadly和爱思助手都无法安装。 Sideloadly提示：
> 
> ```
> FAILED: Call to afc_file_close failed: AFC_E_MUX_ERROR
> ```
> 
> 爱思助手提示：
> 
> ```
> AppexBundleIDNotPrefixed
> ```
> 
> 不知道这些信息有没有用

iOS 15.5 19F77 未越狱
