### ISSUE TITLE
可能存在内存回收问题

### ISSUE THREAD

**Issue by Tilie** [tatsuz0u/EhPanda#16]
使用设备iPhone xr 
系统版本:14.6
使用过程中出现滑动卡顿 
在前台状态下被系统强杀
切换后台后立马被杀
是否存在对图片的资源内存占用的回收问题

**Comment by tatsuz0u** [comment]
您好，

是的，至少在閱讀頁已經確認到有內存洩漏問題。目前沒有打算去解決，待WWDC21更新了SwiftUI框架再考慮。

感謝您的反饋。

**Comment by tatsuz0u** [comment]
Fixed by SwiftUI for iOS 15.
