### ISSUE TITLE
[Feature Request] Clear gallery cache

### ISSUE THREAD

**Issue by b05902034** [tatsuz0u/EhPanda#161]
**Is your feature request related to a problem? Please describe.**
已經下載過的圖片在清空圖片緩存後重新閱讀會出現讀不到的情況
必須手動按reload才會重新顯示

**Comment by tatsuz0u** [comment]
Done. This commit 3de2f78 will be merged into the main branch and released.
(Didn't realize there's a duplicated issue #175 until now...)
