### ISSUE TITLE
[Feature Request] Hide everything until unlocked.

### ISSUE THREAD

**Issue by TigerBeanst** [tatsuz0u/EhPanda#168]
**Describe the solution you'd like**
目前在切回应用或者刚打开时，在开启自动锁定的情况下，即使还没解锁，背景的图片也已经开始加载了。虽然隔着一层高斯模糊，但是还是感觉有点危（
是否可以在启动应用或者切回应用的时候完全隐藏背景（在原有应用上直接盖一层遮罩之类的），在解锁完毕后再展示呢？

**Additional context**
EhPanda v1.3.7(118)

**Comment by tatsuz0u** [comment]
Done. This commit 8fd6ef2 will be merged into the main branch and released.
