### ISSUE TITLE
[BUG] UI size error on iPhone 12

### ISSUE THREAD

**Issue by smounives** [tatsuz0u/EhPanda#169]
**Describe the bug**
网上买了一个某超级签名(个人开发者签名)的服务，然后用v1.3.7_b118签名之后安装到iPhone 12 (iOS15.1)之后打开，界面缩的很小，像iPhone 5s的大小。

**Screenshots**
![image](https://user-images.githubusercontent.com/9267814/139786856-0d724e3c-20e3-467d-8c61-f171e5f75450.png)
![image](https://user-images.githubusercontent.com/9267814/139786870-1aa6f75c-7318-4c80-a2b4-9480882920d2.png)
![image](https://user-images.githubusercontent.com/9267814/139786882-67a28998-0a1e-4f37-aad3-15478e5b7b90.png)

**Please complete the following information:**
 - Device: [e.g. iPhone 12] iPhone 12
 - OS: [e.g. iOS 15] iOS 15.1
 - App Version [e.g. 1.0.3] 1.3.7_b118

**Additional context**

**Comment by tatsuz0u** [comment]
您好，本人開發用機就是 iPhone 12，請透過 AltStore 安裝後再觀察看看。

**Comment by smounives** [comment]
AltStore 安装的可以，但是我还是像用超级签名的方式这样可以一年只用签一次，比较省事，不知道是什么原因造成的

**Comment by tatsuz0u** [comment]
不清楚為什麼會出現，但我不打算為不同安裝方式作特殊處理。
這個 issue 將被關閉。
