### ISSUE TITLE
[BUG] Duplicated pages

### ISSUE THREAD

**Issue by Tilie** [tatsuz0u/EhPanda#17]
使用设备iPhone xr 
系统版本:14.6
举例:翻到20页时出现5-9页内容 然后出现21页

**Comment by tatsuz0u** [comment]
您好，

前一陣子我的確大幅改動了換頁設計，當時測試似乎沒有問題...
請問您使用的是release中的最新版本嗎？我會去嘗試復現它。

感謝您的反饋。

**Comment by Tilie** [comment]
是的 使用的是release中的 v1.0.2_b50版本

**Comment by tatsuz0u** [comment]
經過對19、20、21頁等換頁邊界值的測試，換頁功能似乎運作正常，也未能復現您描述的問題，可以請您確認一下您的帳號是否跟這個issue一樣無法設置為large嗎？

https://github.com/tatsuz0u/EhPanda/issues/15

**Comment by Tilie** [comment]
![IMG_9406](https://user-images.githubusercontent.com/53890473/120913203-d8061180-c6c7-11eb-82f9-a68693270293.PNG)
是指的这个这个选项吗
我也不能百分百复现 昨天一共出现了3-4次这种情况

**Comment by tatsuz0u** [comment]
看起來您的帳號可以設置為large，這沒有問題，那就有些玄學了...

**Comment by tatsuz0u** [comment]
成功復現。

**Comment by tatsuz0u** [comment]
Fixed. https://github.com/tatsuz0u/EhPanda/commit/d71ab89c28930d740ad5755c533483705564a777
