### ISSUE TITLE
[Enhancement] Erase database records with image caches

### ISSUE THREAD

**Issue by a714857512** [tatsuz0u/EhPanda#175]
**Is your feature request related to a problem? Please describe.**
After a period of time, the downloaded pictures may be a month or faster (should be when the app automatically clears the in-app cache), the pictures will not be read, and you must manually click the exclamation points one by one! You can see it again by pressing the button to download. 

**Describe the solution you'd like**
I hope to re-download with a one-click in response to this situation.

**Describe alternatives you've considered**
Or add a button to download those pictures that failed to load

**Comment by tatsuz0u** [comment]
Ah, I forgot to add this feature last time.
OK, I'll do it. 🤨

**Comment by tatsuz0u** [comment]
Done. This commit 3de2f78 will be merged to the main branch and released.
