### ISSUE TITLE
[Feature Request] Page switch when searching

### ISSUE THREAD

**Issue by FlameHaze-ZY** [tatsuz0u/EhPanda#176]
当在主页搜索的时候如果是在搜索栏直接打要搜索的内容，搜索之后右上角没有筛选和页码切换，只有快速搜索或者从点击tag搜索才能筛选和跳转页码。
希望能让直接搜索的时候也能进行页码跳转和筛选

**Comment by tatsuz0u** [comment]
您好，需要使用這些功能之前請先按下檢索旁邊的取消。
因描述無效本 issue 將被關閉。
