### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by FlameHaze-ZY** [tatsuz0u/EhPanda#177]
**Describe the bug**
在一个具体画廊点击搜索一个tag之后，再添加其他如chinese之后搜索如果想要跳转页码就需要取消清空搜索栏再使用跳转功能，但这时候如果正常下拉刷新页数的话就会变成在首页浏览而不是搜索内容。
其实好像这个问题就出现在从画廊进搜索的情况下，在首页这么操作就不会出现bug。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Device: [e.g. iPhone 12]
 - OS: [e.g. iOS 15]
 - App Version [e.g. 1.0.3]

**Additional context**

**Comment by tatsuz0u** [comment]
您好，謝謝反饋，我會去檢查一下。

**Comment by tatsuz0u** [comment]
Done. bee4159
