### ISSUE TITLE
[Feature Request] Reload failed web images

### ISSUE THREAD

**Issue by DRRoJohn** [tatsuz0u/EhPanda#18]
请问大佬能不能加入以下功能：
1、对某一张图片单独刷新。有时候会出现中间有一页加载不出的情况，希望能通过长按该图片等手段对其刷新。
2、页码跳转。比如在预览页直接点击跳转（不过大概需要支持预览整本内容），或者在阅读界面加入滑动块。
最后谢谢大佬！

**Comment by tatsuz0u** [comment]
您好，

都有打算做，但得按實現難度和興趣排著來了。

**Comment by tatsuz0u** [comment]
Previews to reading page navigation, done. [v1.0.3_b68](https://github.com/tatsuz0u/EhPanda/releases/tag/v1.0.3_b68)

**Comment by tatsuz0u** [comment]
Reload failed web images, done.

https://github.com/tatsuz0u/EhPanda/commit/213c527ecf7a106bcfbf40eac6155e0e84c1602f
