### ISSUE TITLE
[Enhancement] Swipe-back behavior optimization

### ISSUE THREAD

**Issue by ASIjacket** [tatsuz0u/EhPanda#180]
**Is your feature request related to a problem? Please describe.**
我经常无法触发手机屏幕左侧的右滑返回，希望可以优化

对比系统app，在列表页面，稍微左上或右下倾斜可以正常触发返回；

ehpanda中对于列表页，只能垂直向右触发，而且左侧的触发边界更窄。稍微倾斜会触发列表滚动，可能是继承了首页调出菜单的设计吧。

**Describe the solution you'd like**
希望可以改进右滑返回体验，
比如增大触发区域或者给列表加遮罩防止滚动。
这只是我大概idea，我不太了解ios开发，希望可以是个有用的思路。

**Comment by tatsuz0u** [comment]
經由其它方式收到反饋詳情，類似 #28，考慮作為後期優化目標。

**Comment by tatsuz0u** [comment]
Done. b711858
