### ISSUE TITLE
解析错误

### ISSUE THREAD

**Issue by Yozoraaa** [tatsuz0u/EhPanda#185]
界面一直显示解析错误，网页端可以正常看。前两个版本还可以正常观看，不知道为什么

**Comment by tatsuz0u** [comment]
您好，請先嘗試重啟 App，這將創建 `EhPanda` 同名檔案或將現存檔案設定為使用。
如果不能解決，嘗試進入 `設定 - 帳號 - 帳號設定` 自行創建或選擇到檔案 `EhPanda`（無需設定為默認），並將 `主頁設定 - 顯示模式` 改為「緊湊」。

**Comment by tatsuz0u** [comment]
因透過其它方式了解到您問題已解決，我將關閉該 issue。
