### ISSUE TITLE
[BUG] A parsing error occurred. Please try again later.

### ISSUE THREAD

**Issue by nm90000** [tatsuz0u/EhPanda#187]
**Describe the bug:**
Error message: "_A parsing error occurred._" on **Home screen** and **Account Configuration**

**To Reproduce:**
- Go to setting -> account settings 
- Log in to E-hentai and Ex-hentai. (can only do both) 
- When you go out of the setting menu leave the tab under ExHentai- this should source the images from Exhentai - I think.
- Go to Home Page
- See Error: "_A parsing error occurred. Please try again later_."
- Alternatively, tap on **Account Configuration** under the **ExHentai** tab 
- See same error message
- Also, if I tap on the "_world_" icon above Account Configuration (the one that's supposed to take you to the OG settings) I only get a blank white page
- The account configuration under E-Hentai works fine - both in-app and OG

**Expected behavior:**
View user uploaded content from both E-hentai and Ex-hentai on the home page

**Screenshots.**
![IMG_0544](https://user-images.githubusercontent.com/95431850/144457561-950c8baf-fdd7-4ce2-979d-660182da13cc.jpg)

**Please complete the following information:**
 - Device: Iphone 13
 - OS: iOS 15
 
**Other:**
- tried to reset my settings in regular browser under ExHentai settings, then logged out and in again in the app. Didn't work. I didn't try to re-install the app though.
- I'm not banned or anything. Ex-hentai works fine in other browsers.

**Comment by tatsuz0u** [comment]
Fixed. 72252a1
