### ISSUE TITLE
[Enhancement] Energy impact

### ISSUE THREAD

**Issue by wangqs97** [tatsuz0u/EhPanda#19]
设备：iPad Pro2018
系统：ios14.3 已越狱
软件版本：v1.0.2_b50

首先感谢作者，非常简洁美观易用的软件。在使用过程中，ipad发热非常严重，耗电也非常厉害，最近发现作者更新了ios15的版本，但普通用户还得等3个月才能用上。

想请问作者是否在之前的版本遇到过类似的问题，以及是否还会在ios14上修复这个问题。

**Comment by tatsuz0u** [comment]
您好，

感謝您對我的app的認可，因本人水平有限，許多問題都只是發現以後記在小本本上繼續觀察...
iOS 15以後的版本得到框架更新的好處，修復了很多影響體驗的問題，特別是首頁的列表性能。
發熱問題一直有注意到，但沒有把它放到功能的優先級以上去處理，不過iOS 15以後的版本這個狀況應該有得到緩解。
除非代價很小，否則未來也不會考慮降低iOS版本要求。

希望以上這些解答了您的疑問。
