### ISSUE TITLE
Tags translation problem: tags are displayed in English or Romaji, not Simplified Chinese.

### ISSUE THREAD

**Issue by shikiroot** [tatsuz0u/EhPanda#193]
OS: iPadOS 15.2
System Language: English
App Language: Simplified Chinese
When I use the app, tags are displayed in English or Romaji, not Simplified Chinese.

**Expected**

![IMG_0022](https://user-images.githubusercontent.com/53338814/148389697-77302093-a075-4dff-afc4-0e63d17babea.JPG)

**Actual**

![IMG_0020](https://user-images.githubusercontent.com/53338814/148389725-a328f8ec-be27-4bc1-b9a1-c4bb42cc5b9d.JPG)

**Comment by tatsuz0u** [comment]
Tags will and should be English unless you turn on the `Translates tags` feature which you can find in `Setting - General`. EhPanda will hide the `Translates tags` switch if it failed to download the translation database. In that case maybe you should fix your network first.

**Comment by leng-yue** [comment]
I found the bug: the version number of the simplified Chinese database was updated to 6. And this will case a `parseFailed` error here: https://github.com/tatsuz0u/EhPanda/blob/3c919cbfdf313d171c5e7586c46e8db724a748ad/EhPanda/Network/Request.swift#L107

**Comment by leng-yue** [comment]
Simply change the version number can fix this bug: #196

**Comment by tatsuz0u** [comment]
I'm terribly sorry!!!
I'll look into it after.

**Comment by tatsuz0u** [comment]
Fixed in #196 by @leng-yue.
