### ISSUE TITLE
[Feature Request] Reload images

### ISSUE THREAD

**Issue by DitFranXX** [tatsuz0u/EhPanda#194]
**Is your feature request related to a problem? Please describe.**
When i visit a gallery which i visited bit times ago, Image load fails. Like image below.
![85411768-DBA7-48E6-9CC6-8F894935C188](https://user-images.githubusercontent.com/45893338/148718429-e1d8ee81-b499-4f73-969a-f0870ada5b18.png)
It can reload as touching middle of error icon. It’s very annoying as i need to touch that icon \*every* page.
It seems like the hath client that used on first time visited is down or address changed.

**Describe the solution you'd like**
Automatically reload these error.

**Describe alternatives you've considered**
Maybe using eh’s server can solve this but its extremely slow.

**Additional context**
Clear image cache doesn’t solve this.
Also. I’m using SNI bypass but it doesn’t affect this one. I think.

**Comment by tatsuz0u** [comment]
Can you tell me the app version?
The latest version of EhPanda should remove database records when clearing the image cache. 🤔

**Comment by DitFranXX** [comment]
I just updated to latest version now. 
Clearing image cache does solve this issue now. Sorry. :sob:

However, I think if there’s automatic reload feature for those error, it will be nice.
I am really enjoying re-reading the ‘gallery’ multiple times. It still annoying that i have to reset record everytime when i got error.

**Comment by tatsuz0u** [comment]
I've just checked the code. Database records of the MPV urls are not getting removed.
Maybe you can consider turning off MPV for EhPanda and wait for the next update. : )

**Comment by DitFranXX** [comment]
I was using quite old version of EhPanda. so It doesn't removed db record.
Now, On latest, 1.5.3. It does remove the record when i clear the cache so it will be reloaded without any error.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tatsuz0u** [comment]
Well, I don't think I can tell which URL is invalid and which isn't. So maybe providing a shortcut to remove records for current gallery is the best I can do.
