### ISSUE TITLE
[BUG]已有功能消失

### ISSUE THREAD

**Issue by glm941214** [tatsuz0u/EhPanda#195]
v1.5.3_b124版本中

1. 标签翻译
2. 点击阅览页面两侧翻页

**貌似遗失了**

**Comment by tatsuz0u** [comment]
您好，感謝您的反饋。剛剛透過測試設備確認該版本沒有發現您提及的兩功能故障。

關於標籤翻譯，請參考我的這篇回答。
https://github.com/tatsuz0u/EhPanda/issues/193#issuecomment-1006599218

關於點擊圖像兩側翻頁，該功能只對水平方向的瀏覽方向有效，如果您設定為垂直方向則不會發生翻頁。

**Comment by glm941214** [comment]
点击阅览页面两侧翻页功能消失的bug依然存在，确定是水平方向，时生效时不生效。而且在浏览页面边缘右滑时，不应该退出浏览，容易误操作。

**Comment by glm941214** [comment]
标签翻译在我这依然没有生效，不清楚是否是设置问题，已更新至最新版本，使用设备是最新正式系统的iPad mini5

**Comment by tatsuz0u** [comment]
最新版本如果無法找到標籤翻譯按鈕可能要檢查網路了，標籤翻譯資料庫保存在 GitHub，不能使用繞過 SNI 阻斷功能。
水平方向如果翻頁失效就的確是非預期行為。
這些問題可能隨著重構消失，請關注下一次更新。

**Comment by tatsuz0u** [comment]
已發佈新版本，請在翻頁失效問題在新版本重現後重新開啟本 issue。

**Comment by glm941214** [comment]
水平方向的翻页完全失效，且左右滑动有明显的顿挫感

**Comment by tatsuz0u** [comment]
> 水平方向的翻页完全失效，且左右滑动有明显的顿挫感

瞭解。因您已另外提出 issue，關於該問題的討論將會在 #209 進行。
