### ISSUE TITLE
[Feature Request]增加本地昵称功能

### ISSUE THREAD

**Issue by glm941214** [tatsuz0u/EhPanda#199]
当初申请账号的时候，随意取了一个用户名，官方修改用户名十分困难。客户端上现在显示的账号名十分碍眼，所以能否提供一个本地昵称的功能呢？谢谢作者大大

**Comment by tatsuz0u** [comment]
您好，我理解您的需要，但是 EhPanda 沒有支援自己帳號體系的打算，因此這樣的功能設計是很令人迷惑的。未發佈的新版本中預計會移除用戶相關資料的展示，如果不移除則會考慮支援隱藏用戶名。
如果以上改動無法滿足您的需要，請考慮向 EH 捐贈以修改用戶名。

**Comment by glm941214** [comment]
感谢，如果可以隐藏也很好
