### ISSUE TITLE
[Feature Request] Waterfall layout

### ISSUE THREAD

**Issue by fightzhi** [tatsuz0u/EhPanda#20]
首页封面缩略图大小感觉有点太小了，能灵活调整会好一些
阅读界面还是缺少引导，我第一次进去甚至出不来
希望能添加左右滑动和跳页的功能，竖向划页就我来说很不习惯
其他都做的挺好，作者加油！

**Comment by tatsuz0u** [comment]
您好，关于您提出的几点建议:
1、请问您使用的是iPad吗？iPad可能会适配单独的列表元素，如果不是的话加入todo list
2、考虑到使用门槛是注册Apple Developer进行自签名安装，我认为加入引导更破坏用户体验
3、duplicate https://github.com/tatsuz0u/EhPanda/issues/3

感谢您的肯定，希望这些回答能令您满意。

**Comment by tatsuz0u** [comment]
Done. https://github.com/tatsuz0u/EhPanda/commit/88741dcc7d36a38a4e7a3abd0de85f3c974ac6cd
