### ISSUE TITLE
[BUG] Sharing images in reading page causes a crash & Clearing gallery history doesn't work

### ISSUE THREAD

**Issue by shikiroot** [tatsuz0u/EhPanda#201]
- Device: iPad Pro 11 gen3
- OS: iPadOS 15.2.1
- App Version v1.5.4_b125

Screen Record

https://user-images.githubusercontent.com/53338814/149611144-5c78168e-2f61-4b30-8f3b-ed78025afb4b.mov

**Comment by tatsuz0u** [comment]
Thanks for your feedback!
This probably will be fixed by refactoring.

**Comment by tatsuz0u** [comment]
I've released EhPanda 2.0. Please feel free to reopen this issue if anyone finds out this bug is reproducible in the new version.
