### ISSUE TITLE
I clicked on an item, but it went to another unrelated item

### ISSUE THREAD

**Issue by alongerya** [tatsuz0u/EhPanda#206]
I clicked on an item, but it went to another unrelated item

It was supposed to be that I would go to whatever item I clicked

I used ios 15.3 and the app version was the latest [v2.0.0_b126]

**Comment by tatsuz0u** [comment]
Thanks for your feedback.
Would you mind to provide the logs and a screen record for debug purpose?

**Comment by tatsuz0u** [comment]
If you are using `Thumbnail` display mode, I've noticed that, gonna look into it soon.

**Comment by alongerya** [comment]
ok,i did use Thumbnail display mode.when i changed to details display mode，it launched fine

**Comment by tatsuz0u** [comment]
> ok,i did use Thumbnail display mode.when i changed to details display mode，it launched fine

I see, it must be the same bug mentioned in #207.

**Comment by alongerya** [comment]
It's really the same bug. Appreciate your help.

**Comment by tatsuz0u** [comment]
Fixed.
