### ISSUE TITLE
[BUG] Unable to navigate to detail page in thumbnail display mode

### ISSUE THREAD

**Issue by chichiwei** [tatsuz0u/EhPanda#207]
**Describe the bug**
在縮圖模式下檢視熱門、標籤、收藏介面時，點選任一圖片無法正確進入所選之閱讀介面

**To Reproduce**
1.進入熱門、標籤、收藏介面
2. 單擊任一圖片，進入閱讀介面
3. 發現該介面並非所選圖片之漫畫內容

**Expected behavior**
應該能正確進入所選圖片的閱讀介面

**Screenshots**
https://i.imgur.com/Xi6X6N8.mp4

**Please complete the following information:**
 - Device: iPad mini5
 - OS: iOS 15.0.2
 - App Version: v2.0.0_b126

**Comment by tatsuz0u** [comment]
感謝您的反饋。
這的確是個 bug，我會盡快處理。

**Comment by tatsuz0u** [comment]
Fixed.
