### ISSUE TITLE
[BUG]iPad mini5上左右点击翻页功能失效

### ISSUE THREAD

**Issue by glm941214** [tatsuz0u/EhPanda#209]
**Describe the bug**
经过测试，在iPhone12上，左右点击翻页功能正常，在iPad mini5上，该功能失效。此外，希望移除点击翻页时的滑动特效，这在非高刷新率的平板上体验不好，谢谢作者的付出。

**Comment by glm941214** [comment]
在iPhone12上也出现了失效

**Comment by tatsuz0u** [comment]
感謝您的反饋。
方便將日誌發給我看一看嗎？可以發送郵件到我的 GitHub profile 上的郵箱或 Telegram。

**Comment by tatsuz0u** [comment]
您的日誌收到了，謝謝。

**Comment by tatsuz0u** [comment]
您好，剛剛查看了您的日誌。
內容顯示在 iPad 上每次識別到的單次點擊手勢中，每一次都執行了顯示/隱藏控制面板。
而在 iPhone 上則是前面數次執行了翻頁，後面數次執行了顯示/隱藏控制面板。
（點擊螢幕的兩側 20% 區域為翻頁，點擊中間 60% 區域為顯示/隱藏控制面板。）

請問您所說的功能失效具體是怎樣的表現呢？

**Comment by glm941214** [comment]
确定是点击了两侧的20%区域， 间歇性正常，暂未发现触发原因，有空我录一个视频。

**Comment by tatsuz0u** [comment]
明白了，但暫時不需要錄影。這一塊最近需要改動，下一個版本應該會順帶修復。

**Comment by tatsuz0u** [comment]
即將發佈 2.1.1 版本。
如果在新版本發現此問題歡迎再次開啟本 issue。

**Comment by glm941214** [comment]
依然存在，难道您没有出现过该问题吗？应该是一个能轻易触发的问题 = =

**Comment by tatsuz0u** [comment]
是的，沒有遇到過，暫時也沒有其它人回報這個問題。
如果您在新版本有遇到可以重開本 issue。
另外如果方便的話希望可以也提供螢幕錄像。

**Comment by kiponfu** [comment]
我也遇到了这个问题，在iphone12pro上，点击页面两侧不是翻页而是呼出/隐藏了控制面板
