### ISSUE TITLE
[BUG]檢視標籤搜索介面時,單擊圖片無法顯示閱讀頁面

### ISSUE THREAD

**Issue by chichiwei** [tatsuz0u/EhPanda#210]
**Describe the bug**
在閱讀詳情頁面，點選標籤導航後，單擊任一圖片無法顯示閱讀介面

**To Reproduce**
1. 進入閱讀詳情頁面
2. 單擊標籤進入搜索頁面
3. 點選任一圖片
4. 無法顯示閱讀介面

**Expected behavior**
應能正確顯示閱讀介面.

**Screenshots**
https://imgur.com/a/urMJRpx
https://i.imgur.com/WtONNWr.mp4
https://i.imgur.com/E2Ja2x6.mp4
https://i.imgur.com/HgVSEnx.mp4
https://i.imgur.com/2hTEzEt.mp4

**Please complete the following information:**
 - Device: iPad mini5
 - OS: iOS15.0.2
 - App Version: v2.1.0_b127

**Comment by tatsuz0u** [comment]
Fixed. 66ac3cd
