### ISSUE TITLE
[BUG]筛选页面中，评分下限栏目文字显示有误

### ISSUE THREAD

**Issue by Morax-xyc** [tatsuz0u/EhPanda#211]
**Describe the bug**
当点击评分下限栏时，会弹出四个选项且内容与当前选项一致。当选择最上面那个时，评分下限栏将变成“5星”，再次点击，弹出选项内容将全部变为5星，以此类推。

**To Reproduce**
1. 搜索任意内容
2. 右上角点击后选择“筛选”
3. 打开“高级选项”按钮
4. 下滑至“评分下限”
5. 打开“评分下限设置”
6. 在“评分下限”中选择

**Expected behavior**
点击评分下限后会出现“2星”到“5星”的选项，且不随着选择而改变

**Screenshots**
[视频（点击打开）](https://jbhdf-my.sharepoint.com/:v:/g/personal/xyc_jbhdf_onmicrosoft_com/EZ5ohzudrOBEhF6zcxhB-rAB6134PMvfnQs7Tr6zaI38CA?e=Iy2Ylg)

**Please complete the following information:**
 - Device: [ iPhone 12]
 - OS: [ iOS 15.3 ]
 - App Version [ 2.1.0 ]

**Comment by tatsuz0u** [comment]
Fixed. c6422d8
