### ISSUE TITLE
[BUG] Failed in bringing up keyboard on iPad

### ISSUE THREAD

**Issue by chichiwei** [tatsuz0u/EhPanda#216]
**Describe the bug**
首頁、排名頁面右上角的篩選功能，以及收藏、搜尋頁面右上角的搜尋功能，
來回交替使用這些功能時，可能導致功能失常

**To Reproduce**
1. 進入首頁或排名頁面
2. 點擊右上角的篩選
3. 切換至收藏頁面，點擊右上角的搜尋，該功能失效
4. 切換至搜尋頁面，點擊右上角的搜尋，該功能失效

**Expected behavior**
功能應可正常使用

**Screenshots**
https://i.imgur.com/rnZbDk6.mp4
https://i.imgur.com/38h7D5b.mp4
https://i.imgur.com/aGrCRN9.mp4

**Please complete the following information:**
 - Device: [iPad mini5]
 - OS: [ iOS 15.0.2]
 - App Version [v2.1.1_b128]

**Comment by tatsuz0u** [comment]
您好，感謝您的反饋。我會儘快處理。

**Comment by chichiwei** [comment]
> 經測試在 iPadOS 15.3 的 iPad mini 6 上未能重現此問題。 有另一例為用戶反饋在 iPadOS 15.4 上未能重現此問題。 可能需要請您考慮升級 iPadOS 版本。🙇‍♂️

已更新至 iPadOS 15.3，問題已消失，感謝回覆：）
