### ISSUE TITLE
AltStore安装必须iOS15？

### ISSUE THREAD

**Issue by Golubb** [tatsuz0u/EhPanda#22]
用AltStore安装提示要求iOS 15.0，低版本iOS不支持？

**Comment by tatsuz0u** [comment]
![image](https://user-images.githubusercontent.com/31207151/123721822-aee93300-d8b9-11eb-9fbe-1f9fa9f7f15b.jpeg)
![image](https://user-images.githubusercontent.com/31207151/123721830-b3155080-d8b9-11eb-8845-110ddbbd65c0.jpeg)
