### ISSUE TITLE
[BUG]Cannot install in iPad Pro

### ISSUE THREAD

**Issue by artoodetoo3301** [tatsuz0u/EhPanda#234]
**Describe the bug**
iPad OS stated it does not work with this version of iOS.

**Screenshots**

**Please complete the following information:**
 - Device: iPad Pro 2018
 - OS: iOS 15.3.1

**Comment by tatsuz0u** [comment]
Please provide more details.

**Comment by artoodetoo3301** [comment]
Please close the issue, it is solved.
