### ISSUE TITLE
[BUG] Tag translation causes extremely low performance

### ISSUE THREAD

**Issue by frankkly** [tatsuz0u/EhPanda#237]
**Describe the bug**
启用标签扩展后，整个App会变得非常卡顿，经过多次尝试发现只要关闭了翻译标签之后就不会卡顿了

**Please complete the following information:**
 - Device: [iPhone 11 Pro Max]
 - OS: [iOS 15.3.1]
 - App Version [2.3.0(134)]

**Comment by tatsuz0u** [comment]
Fixed. d1b5255
