### ISSUE TITLE
[BUG]iPad端收藏页面，点击顶部排序图标后任何本子点击都无响应，不会进入详细页面。

### ISSUE THREAD

**Issue by Enderzeal** [tatsuz0u/EhPanda#240]
**Describe the bug**
iPad端收藏页面，点击顶部排序图标后任何本子点击都无响应，不会进入详细页面。

 - Device:iPad Air 3
 - OS:iPadOS 15.3.1
 - App Version 2.3.1

**Comment by tatsuz0u** [comment]
您好，感謝您的反饋。但是我未能重現您描述的問題，希望您可以附上從重啟 app 到重現問題為止的螢幕錄像。🙇‍♂️

**Comment by Enderzeal** [comment]
我自己也无法复现了，关闭issue吧。
