### ISSUE TITLE
[Question] homebrew location

### ISSUE THREAD

**Issue by superarts** [tatsuz0u/EhPanda#244]
I noticed that in run script phase, `homebrew` location is not very flexible:

```
if test -d "/opt/homebrew/bin/"; then
  PATH="/opt/homebrew/bin/:${PATH}"
fi
```

From homebrew:

```
This script installs Homebrew to its preferred prefix (/usr/local for macOS Intel, /opt/homebrew for Apple Silicon and /home/linuxbrew/.linuxbrew for Linux)...
```

Since Intel mac is still a thing, would it be better to `export` both paths please?

**Comment by tatsuz0u** [comment]
I think an Intel Mac doesn't need to export the path.
It just works. 🤔

**Comment by superarts** [comment]
Weird, it didn't work me, I manually updated it to get it to work. Anyway we can close this issue and if someone else reports it, hopefully he can get here using search.

Anyway thanks for the great work! I jerked off 3 times today due to the awesomeness of this project.
