### ISSUE TITLE
[Enhancement] Better UX in filters setting

### ISSUE THREAD

**Issue by MMMrJoker** [tatsuz0u/EhPanda#25]
1. 点解详情页面中的对应类别进入该分类的浏览列表：如点击同人志进入同人志列表
![image](https://user-images.githubusercontent.com/86755049/124693337-d40d1f80-df11-11eb-9943-e510c6681834.png)
2.优化筛选页的操作：长按同人志为仅搜索同人志，再次长按为仅不搜索同人志
![image](https://user-images.githubusercontent.com/86755049/124693474-19c9e800-df12-11eb-8678-2fdaa26eb5fd.png)
3.在浏览页面高亮关注的tag
![微信图片_202107071102061111jpg](https://user-images.githubusercontent.com/86755049/124694088-2dc21980-df13-11eb-8381-0873a536748c.jpg)
4.添加图片刷新功能：因不可抗力造成图片509后无法通过任何办法来刷新图片

最后非常感谢作者抽空阅读我的浅见，最后祝你身体健康，事业顺利。

**Comment by tatsuz0u** [comment]
您好，感谢您为这个app提出的建议

1. 这里会存在两个问题，在什么类型的列表中根据该分类进行筛选，以及它看起来不能交互。
2. 这个做起来不会有什么问题，我可以去调研一下。
3. 在列表中的tag显示目前存在很影响体验的问题，所以我给这个功能标记上了⚠️，在它可用之前我可能不会添加任何增强功能。
4. 这个已经有准备做，跟其它阅读页优化项一起。

希望以上内容能让您满意。

另外，看起来您正在使用的是v1.0.2的EhPanda，鉴于v1.0.2不再会获得任何更新，我会建议您在iOS 15正式版可用后更新到v1.0.3以获得包括性能、功耗、稳定性等优化及更多功能。

**Comment by MMMrJoker** [comment]
> 您好，感谢您为这个app提出的建议
> 
> 1. 这里会存在两个问题，在什么类型的列表中根据该分类进行筛选，以及它看起来不能交互。
> 2. 这个做起来不会有什么问题，我可以去调研一下。
> 3. 在列表中的tag显示目前存在很影响体验的问题，所以我给这个功能标记上了⚠️，在它可用之前我可能不会添加任何增强功能。
> 4. 这个已经有准备做，跟其它阅读页优化项一起。
> 
> 希望以上内容能让您满意。
> 
> 另外，看起来您正在使用的是v1.0.2的EhPanda，鉴于v1.0.2不再会获得任何更新，我会建议您在iOS 15正式版可用后更新到v1.0.3以获得包括性能、功耗、稳定性等优化及更多功能。
