### ISSUE TITLE
[Feature Request] Tags translation

### ISSUE THREAD

**Issue by xioxin** [tatsuz0u/EhPanda#26]
增加中文标签翻译，如果能增加搜索标签填充提示就更好了。

中英对照数据
https://github.com/EhTagTranslation/Database
https://github.com/EhTagTranslation/Database/wiki/%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97

这个数据在浏览器的翻译插件
https://github.com/EhTagTranslation/EhSyringe

**Comment by tatsuz0u** [comment]
您好，感謝您提出的建議，專門找來相關repo地址讓人感到十分親切。這項功能已有準備開發，關注是否有相關分支開設或後續更新就可以喔。

**Comment by tatsuz0u** [comment]
Done. https://github.com/tatsuz0u/EhPanda/releases/tag/v1.0.3_b75
