### ISSUE TITLE
[Feature Request] Dual page reading

### ISSUE THREAD

**Issue by vecStardo** [tatsuz0u/EhPanda#27]
因为没升级到ios15的原因不知道1.0.3中有没有加入分页功能。
但是先斗胆提出希望加入分页的需求和既然搞了pad的适配不如干脆点让页面在pad上左右显示

十分感谢大佬的开发，真是救我狗命了

**Comment by tatsuz0u** [comment]
您好，这个功能有计划开发，请等待后续更新。

**Comment by vecStardo** [comment]
好的，十分期待
看了看提交记录真是吓人啊，更新虽好，也要注意身体啊。加油

**Comment by tatsuz0u** [comment]
Done. https://github.com/tatsuz0u/EhPanda/releases/tag/v1.0.3_b72
