### ISSUE TITLE
[BUG] New dawn view clipping in iPad multi-task

### ISSUE THREAD

**Issue by vecStardo** [tatsuz0u/EhPanda#29]
**Describe the bug**
小窗模式下黎明问候显示不完全

**To Reproduce**
1. 使用小窗模式打开app
2. 触发黎明问候

**Expected behavior**
正确显示图片

**Screenshots**
![473B94F5-19FF-418B-A69D-84997CEF8844](https://user-images.githubusercontent.com/76275318/126217653-0f5a4be4-0f3e-4b78-a5f7-04a3485722f3.png)

**Please complete the following information:**
 - Device: iPad Pro2020
 - OS: ios15
 - App Version 1.0.3

**Additional context**

**Comment by tatsuz0u** [comment]
您好，
這個看起來是是因為使用了屏幕寬度而非窗口寬度導致的缺陷，可以提供詳細的build號嗎？因為這個問題曾被處理過一次。
感謝您的反饋，能截圖到這個場景的缺陷實在是很不容易😆。

**Comment by vecStardo** [comment]
> 您好，
> 這個看起來是是因為使用了屏幕寬度而非窗口寬度導致的缺陷，可以提供詳細的build號嗎？因為這個問題曾被處理過一次。
> 感謝您的反饋，能截圖到這個場景的缺陷實在是很不容易😆。

1.0.3b_57应该

**Comment by tatsuz0u** [comment]
> > 您好，
> 
> > 這個看起來是是因為使用了屏幕寬度而非窗口寬度導致的缺陷，可以提供詳細的build號嗎？因為這個問題曾被處理過一次。
> 
> > 感謝您的反饋，能截圖到這個場景的缺陷實在是很不容易😆。
> 
> 
> 
> 1.0.3b_57应该

好的，已經定位到原因，下一版本會修復這個問題。
