### ISSUE TITLE
[Feature Request] Reading direction

### ISSUE THREAD

**Issue by samong2** [tatsuz0u/EhPanda#3]
Hi
A good application with advanced options for searching.
Although the viewer's reading direction is vertical,
I'd like to add left-to-right or right-to-left.

**Comment by tatsuz0u** [comment]
(Since you're not submitting a pull request but an issue, I'll consider it as a feature request.)

Thanks for using my app.
As for the feature you mentioned, providing multiple reading direction is already on my TODO list.

**Comment by tatsuz0u** [comment]
Done. [v1.0.3_b68](https://github.com/tatsuz0u/EhPanda/releases/tag/v1.0.3_b68)
