### ISSUE TITLE
[Feature Request] Make keywords editable after clicking a tag

### ISSUE THREAD

**Issue by vecStardo** [tatsuz0u/EhPanda#30]
**Is your feature request related to a problem? Please describe.**
目前在点击一个标签时会直接搜索该标签，但是这个搜索条件无法编辑，比如我点击一个作者标签，这时候往往想增加xp tag或者翻译条件。
**A clear and concise description of what you want to happen.**
搜索条件可以编辑

**Comment by tatsuz0u** [comment]
您好，感謝您提出這個建議，我會在完成基本瀏覽的體驗優化後考慮這一塊。

**Comment by tatsuz0u** [comment]
Done

https://github.com/tatsuz0u/EhPanda/commit/c8c5ce77fcac8d5c5ef39e0c729503bc93cf27d7
