### ISSUE TITLE
[Enhancement]ios14

### ISSUE THREAD

**Issue by 2383741765** [tatsuz0u/EhPanda#34]
请问，ios14还会更新吗，拥有ios15新功能，比如阅读方向（左右滑动）

**Comment by tatsuz0u** [comment]
您好，目前我没有继续兼容iOS 14或功能下放的打算。

**Comment by 2383741765** [comment]
谢谢回复，大神，我发现我表达不够清楚，打字漏字了，我原本想问，以后ios14还会更新吗，不管多久！！！

**Comment by 2383741765** [comment]
谢谢回复，大神，我发现了我表达的经典，打字漏字了，我还有下次更新吗，不管多久！！！

**Comment by 2383741765** [comment]
谢谢回复，大神，我发现了我表达得不够清楚，打字漏字了，我还有下次更新吗，不管多久！！！

**Comment by 2383741765** [comment]
谢谢大神！还是希望能看到14的更新，不管多久！！！

**Comment by tatsuz0u** [comment]
除非有足够的需求（比如我发现在iOS 15正式版发布后三个月我的用户75%以上还在使用iOS 14）和合理的理由（比如iOS 15存在不适合使用的因素），iOS 14版本的功能更新、漏洞修复会永久停止。

**Comment by 2383741765** [comment]
明白！
