### ISSUE TITLE
[BUG] Bypass SNI filtering feature doesn't work with WebImage in some eh hosts

### ISSUE THREAD

**Issue by 2383741765** [tatsuz0u/EhPanda#35]
ios14实验室功能ex网站预览图加载不出来，e站正常；挂vpn后ex站预览图可以加载出来，不是我的账户问题。我在打开实验室功能的情况下进入用户设置发现两个站点的缩略图设置不同，e站的设置是最小缩略图，ex站的设置是紧凑缩略图，我试图改变用户设置，但是我发现我改不了实验室功能的用户设置

**Comment by tatsuz0u** [comment]
您好，刚才经过测试，在v1.0.3_b75版本下，打开域前置绕过SNI阻断功能后，不使用代理的情况下能够正常获取到不同站点选项下的预览图。
您所遇到的情况有多个因素影响，该功能本身比较依赖于网络自身品质，且里站访问速度本身会较表站慢一些。希望这些解答了您的问题。

**Comment by 2383741765** [comment]
![1](https://user-images.githubusercontent.com/88372591/128675935-e61cdad2-389f-4355-943a-d1061ffbf530.jpg)
![2](https://user-images.githubusercontent.com/88372591/128675940-a08bb46b-93b5-4899-89a8-c7cdbdc64454.jpg)
![3](https://user-images.githubusercontent.com/88372591/128675946-04e5e9c6-92e8-4720-8f5c-5dda0baf5640.jpg)
![4](https://user-images.githubusercontent.com/88372591/128675957-fc4368cc-cacb-4ecb-aa22-b3d78428b136.jpg)
![11](https://user-images.githubusercontent.com/88372591/128676015-40cb8554-c313-45d6-837a-9e853ece1b12.jpg)
![22](https://user-images.githubusercontent.com/88372591/128676026-fd2811d3-1f93-440a-bb59-c208bbc1b483.jpg)
![33](https://user-images.githubusercontent.com/88372591/128676046-7fd2aef2-f32e-4fd0-941e-e72d193cdae8.jpg)
![44](https://user-images.githubusercontent.com/88372591/128676052-0d52cf33-539c-4315-a894-4d3ed2567a7a.jpg)

**Comment by 2383741765** [comment]
大神，我将iPad8更新到ios15beta4后，依旧不行，不知道是什么原因，挂代理就可以预览。。。

**Comment by 2383741765** [comment]
网络的话，我在安卓上面不用代理，也是没问题可以预览的，里站=-=

**Comment by tatsuz0u** [comment]
非常抱歉，再次测试确定这个问题确实存在，该问题的修复会跟随b76版本发布，敬请关注。

**Comment by tatsuz0u** [comment]
Done.
