### ISSUE TITLE
[Enhancement] Make app-lock feature available after exiting the app

### ISSUE THREAD

**Issue by glm941214** [tatsuz0u/EhPanda#36]
**Describe the bug**
图片加载失败后无法重新加载，APP打开时没有触发密码锁的问题。

**To Reproduce**
1、浏览时关闭APP后，再次打开，当前图片以及后续几张图片不再继续加载，且无法再次加载；清空图片缓存并退出APP，已加载的图片会消失，但无法重新加载，目测是触发加载的逻辑存在问题，建议每次翻页时检测当前页是否存在图片文件。
2、APP打开时没有触发密码锁，仅在切换APP后切回时会触发，且触发存在一定概率无法触发的问题。

**Please complete the following information:**
 - Device: [e.g. iPad Air3]
 - OS: [e.g. iOS 15]
 - App Version [e.g. 1.0.3]

**Additional context**
感谢作者的辛勤付出！

**Comment by tatsuz0u** [comment]
您好，对于第一个问题，打算加入图片手动刷新机制来处理这一类错误情况，已有相关issue。
第二个的话，其实是设计时没有考虑过这一点，原意是想避免有人看到你正在阅读的东西，而不是避免有人能访问这个app。

我会对第二个问题进行调研后考虑是否修改逻辑，感谢您的反馈，希望这些回答能让您满意。

**Comment by tatsuz0u** [comment]
Done. 53a68c6252ad01614649d2af11fa572d5271b844
