### ISSUE TITLE
[BUG]v1.0.3_b76版本无限闪退

### ISSUE THREAD

**Issue by aoki-rin** [tatsuz0u/EhPanda#40]
**Describe the bug**
一点开图标就闪退，主界面都开不到，v1.0.3_b75能够正常使用

**Please complete the following information:**
 - Device: [e.g. iPad 第五代]
 - OS: [e.g. ios 15]
 - App Version [v1.0.3_b76]

**Additional context**

**Comment by tatsuz0u** [comment]
Duplicated. #33

**Comment by aoki-rin** [comment]
我使用的是ipad os beta4，ehpanda版本也是最新的v1.0.3_b76。还是存在无限闪退的问题

**Comment by tatsuz0u** [comment]
因為你應當使用iOS beta 5。

**Comment by tatsuz0u** [comment]
因為你應當使用iOS beta 5。
