### ISSUE TITLE
[BUG]语言排除设置无法正确应用

### ISSUE THREAD

**Issue by aoki-rin** [tatsuz0u/EhPanda#41]
**Describe the bug**
在e-hentai网页设置中设置语言排除选项后依然会显示该语言的画廊。
在app账户设置中没有找到语言排除项设置。

**Comment by tatsuz0u** [comment]
您好，EhPanda会在条件允许的情况下在您账户下创建一个名为"EhPanda"的profile，因此您的网站设置不一定会生效，碰巧语言排除选项没有在原生Eh设置中实现，建议您点击该Eh设置功能右上角的web入口进行配置。
