### ISSUE TITLE
[Feature Request] Current page number and total page number function

### ISSUE THREAD

**Issue by a714857512** [tatsuz0u/EhPanda#43]
**Is your feature request related to a problem? Please describe.**
大佬好强，感谢大佬。不知道1.0.4版本有没有当前是第几页的页数显示。

**Describe the solution you'd like**
在漫画列表页面显示当前检索总页数和当前所在的页数。

**Describe alternatives you've considered**
例如在页面右下角显示一个圆形按钮，上面显示当前页数和总页数。点击的时候有个弹窗可以修改当前页数，确认后可以快速跳转到该页进行获取数据。类似网页跳转后，还可以下拉获取之前的页数的数据，以及上拉获取之后页数的数据。

**Additional context**

**Comment by tatsuz0u** [comment]
您好，
页数相关的数据其实一直都有，实现这个功能也不难而且有必要。
不过要先让我想想UI要怎么放比较合适...
感谢您的建议。

**Comment by tatsuz0u** [comment]
Done. 0153c3e128f21af92f504f348a2b90198881291f

**Comment by a714857512** [comment]
> 完毕。[0153c3e](https://github.com/tatsuz0u/EhPanda/commit/0153c3e128f21af92f504f348a2b90198881291f)

取消关键词搜索后，下拉刷新会变成无关键词搜索。

**Comment by tatsuz0u** [comment]
> > 完毕。[0153c3e](https://github.com/tatsuz0u/EhPanda/commit/0153c3e128f21af92f504f348a2b90198881291f)
> 
> 
> 
> 取消关键词搜索后，下拉刷新会变成无关键词搜索。

修好了。https://github.com/tatsuz0u/EhPanda/commit/68ee083860f746a4cf12eb096e4f86e27425eac3

不關聯的問題希望可以開一個新 issue 來說明。
謝謝您的反饋。
