### ISSUE TITLE
[Feature Request] PageSlider, Tags Interaction

### ISSUE THREAD

**Issue by kiddliao** [tatsuz0u/EhPanda#6]
有时候几百面的漫画 想看看最新的几话 要一点点翻就很久 而且每次翻到底只能翻几面 还要等下一次加载才能继续翻页

**Comment by kiddliao** [comment]
还有搜索历史 每次打开软件要重新把每个标签输入才能搜索 没有历史记录不太方便

**Comment by kiddliao** [comment]
而且点击app里面的标签 也没法进行复制 如果想自己自定义搜索 还得一边输入标签一边看看标签

**Comment by tatsuz0u** [comment]
感谢您对我的app提出宝贵意见。

1. 分页及进度条功能目前在我的制作规划中。
2. 鉴于我个人的审美倾向，不太能接受从输入框延伸出一个面板来呈现更多信息这种设计。而将搜索单独成页需要考察是否影响用户体验的连续性。因此对于这个功能，我认为我还需要更多时间思考实现细节。
3. 复制标签内容，我印象中EH还可以给标签投票，考虑放在一起做。我对自定义搜索的标签补全方面有着与搜索历史同样的顾虑，需要思考实现细节。

希望这个答复能让您满意。

**Comment by kiddliao** [comment]
大佬加油

**Comment by honjow** [comment]
大佬加油

**Comment by tatsuz0u** [comment]
> 还有搜索历史 每次打开软件要重新把每个标签输入才能搜索 没有历史记录不太方便

Done.

**Comment by tatsuz0u** [comment]
PageSlider done. [v1.0.3_b68](https://github.com/tatsuz0u/EhPanda/releases/tag/v1.0.3_b68)
