### ISSUE TITLE
[Feature Request] Copy gallery infos

### ISSUE THREAD

**Issue by TeoZler** [tatsuz0u/EhPanda#7]
如题，希望在画廊详情页时，长按画廊名时可以进行复制

**Comment by TeoZler** [comment]
主要是想复制出来分享给沙雕网友（
只要日文就行

**Comment by tatsuz0u** [comment]
看来是时效性要求不高的使用场景，我会考虑以复制详细信息的形式加入。

**Comment by tatsuz0u** [comment]
Done. https://github.com/tatsuz0u/EhPanda/releases/tag/v1.0.4_b78
