### ISSUE TITLE
强烈希望终有一天可以兼容IPad

### ISSUE THREAD

**Issue by karanokyoukai** [tatsuz0u/EhPanda#8]

**Comment by tatsuz0u** [comment]
您好，是兼容的，但未做优化。

**Comment by tatsuz0u** [comment]
明白了，看漏了是吗...
我们可能都有过黑历史，但没有多少机会洗白。
你需要我删除这个issue吗？

**Comment by karanokyoukai** [comment]
不是的，纯属嘴快说错了...
是在pad上试了试有点别扭，希望有机会可以优化一下。
另外，麻烦删除，谢谢（
