### ISSUE TITLE
[BUG]Japanese Title cannot be displayed correctly（copy）

### ISSUE THREAD

**Issue by aoki-rin** [tatsuz0u/EhPanda#88]
**Describe the bug**
画廊信息中无法显示（复制)日文标题

**Please complete the following information:**
 - Device: ipad
 - OS: iOS 15
 - App Version 1.1.1

**Additional context**
![IMG_2146](https://user-images.githubusercontent.com/88824899/132976876-4ad75307-29c2-4990-b42f-2ed67553b963.PNG)
![IMG_2147](https://user-images.githubusercontent.com/88824899/132976880-d106c41f-e751-49ac-9142-831fb5f28135.PNG)
![IMG_2148](https://user-images.githubusercontent.com/88824899/132976881-33daca81-8131-4f31-9b29-3c8cc21695c1.PNG)
![IMG_2149](https://user-images.githubusercontent.com/88824899/132976885-386afaed-cfe4-4e90-ba9f-6b35c45f9755.PNG)

**Comment by tatsuz0u** [comment]
OK, thanks for your feedback, I'll look into it.

**Comment by tatsuz0u** [comment]
Fixed. https://github.com/tatsuz0u/EhPanda/releases/tag/v1.1.2_b106
