### ISSUE TITLE
[Feature Request] A shortcut to append tags filter

### ISSUE THREAD

**Issue by k2rr** [tatsuz0u/EhPanda#9]
首先感谢大佬的开发
和介绍的一样，非常优雅的UI。
希望在筛选器中添加一个快捷添加TAG的功能，
例如：多出一个中文选项 ，开启即默认在搜索栏文本中添加chinese，此时搜索NTR即自动搜索ntr chinese。
以及筛选器中自动显示上次观看的漫画的TAG，勾选即添加。
具体逻辑可以看这位的项目
https://github.com/DaidoujiChen/Dai-Hentai
最后感谢大佬的劳动！

**Comment by tatsuz0u** [comment]
感谢您为这个项目提出建议。
我会考虑制作的。

**Comment by tatsuz0u** [comment]
EhPanda 新增了快速檢索功能，可以自行編輯檢索詞內容及其別稱，考慮到不希望更改現有檢索邏輯和有部分功能重疊，決定不開發。
同樣地，我希望 EhPanda 的功能不偏向於任何一個地區的用戶，單一語言特化的功能是不太可能開發的。但由於新增了原生的 Eh 網站設定功能，可以更方便地修改包括 EhPanda 專屬檔案在內的所有 Eh 網站設定，如果長期需要可以在裡面設定排除中文以外的語言，如果臨時需要排除恐怕只能手動了。凡事有例外，如果臨時設定只顯示某個語言的功能呼聲很大，我會嘗試開發一個更通用、能為多個地區用戶帶來便利的功能以滿足需求。

希望以上解釋能夠讓您滿意。我將關閉這個 issue。
